### ISSUE TITLE
error when posting

### ISSUE THREAD

**Issue by gotdirt24** [TimPaterson/Fusion360-Batch-Post#16]
i tried using it today im getting failed 0 files were written . 1 setups were skipped due to error; failed on setup (name of setup);
fusion360 reported an exception
funny thing is this file/setup has not changed last week it posted fine i have tried changing the timing and naming to test it 
 i did remove the preceded gode lines its was redundant

**Comment by TimPaterson** [comment]
How many operations are in the setup?  If more than one, verify you can run the normal Fusion 360 post process command on each of them individually.  If that works, suppress all but one operation and see if some work with PostProcessAll and some don't.  You can use multiple select on the operations, right click and check/uncheck Suppress.  Make sure you have the latest version --  a bug in handling suppressed operations was fixed last month.

**Comment by gotdirt24** [comment]
No matter what I do I keep getting that error 
I have suppressed each operation still have a error and I can post the regular way one by one 
Would you be willing to teamviewer in ?

Thanks mike

**Comment by gotdirt24** [comment]
i tried installing post process all again with the newest github code it
does create a file to the output folder but empty 0kb

**Comment by TimPaterson** [comment]
I forgot to ask the most basic question: What post processor are you using?

**Comment by gotdirt24** [comment]
https://swissi2000.github.io/Fusion-360-Milling-Post-Processor-for-Centroid/

**Comment by TimPaterson** [comment]
I was able to reproduce the problem with that post processor, which led to a simple fix. Get the latest version and give it a try (restart the add-in if Fusion 360 is running).

If it works for you, please also confirm what tool change code to use so I can update my compatibility table.

**Comment by gotdirt24** [comment]
Very cool that’s maybe the most common post processor people are using for centroid it has a bunch of bells and whistles 
I will check it out tonight see how it goes

**Comment by gotdirt24** [comment]
Added new code 
It’s doing something different

**Comment by gotdirt24** [comment]
I have good news I did get it to work a few times and run the program everything worked as planned 
, there is a tool path grafting that is displayed Before the program starts that isn’t correct but the gcode is

**Comment by TimPaterson** [comment]
I guess we're done then...
